version: '3'

services:
  secexlog_server:
    image: secexlog/back-end
    container_name: secexlog_server
    ports:
      - 3333:3333

  secexlog_mysql:
    image: bitnami/mysql:latest
    container_name: secexlog_mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - ${MYSQL_MASK_PORT}:${MYSQL_PORT}
    networks:
      - mysql-compose-network

  secexlog_adminer:
    image: adminer
    container_name: secexlog_adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  secexlog_redis:
    image: bitnami/redis:latest
    container_name: secexlog_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_MASK_PORT}:${REDIS_PORT}

networks:
  mysql-compose-network:
    driver: bridge
